AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  serverless-bc-inference
  SAM Template for serverless-bc-inference Lambda function for lambda_function serveless inference
Resources:
  LambdaFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: /
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      Timeout: 60
      MemorySize: 256
Outputs:
  LambdaFunction:
    Description: "lambda_function Inference Lambda Function ARN"
    Value: !GetAtt lambda_function.Arn
